require("manzoli.core.options")
require("manzoli.core.colorscheme")
require("manzoli.plugins-setup")
require("manzoli.plugins.nvim-tree")
require("manzoli.plugins.lualine")
require("manzoli.plugins.lsp")
require("manzoli.plugins.treesitter")
