require("manzoli.plugins-setup")
require("manzoli.core.options")
require("manzoli.core.keymaps")
require("manzoli.core.colorscheme")
require("manzoli.plugins.nvim-tree")
require("manzoli.plugins.telescope")
require("manzoli.plugins.lualine")
require("manzoli.plugins.nvim-cmp")